### ISSUE TITLE
Unsafe to close channel after calling Conn.RemoveSignal

### ISSUE THREAD

**Issue by jhenstridge** [godbus/dbus#158]
If one part of my program is no longer interested in receiving D-Bus signals, it can call `RemoveSignal` to unregister the channel it provided.  At this point it would make sense to close the channel to release its resources.

However, if the channel is unbuffered or the buffer has filled up, this can lead to a panic.  While the RWLock should prevent new signals from being delivered to the channel, we could have goroutines waiting to send old signals on the channel:

https://github.com/godbus/dbus/blob/master/default_handler.go#L263-L269

It looks like the only thing that will cause these goroutines to clear is `defaultSignalHandler.Terminate`, which won't be called until the program is exiting.

The only way to avoid this seems to be to choose a channel buffer large enough that no goroutines will be spawned to handle signal broadcasts in the time it takes to acquire the write lock.  That's going to give a program that works most of the time, but may panic under load.

**Comment by jhenstridge** [comment]
Here is a short test program demonstrating the panic:

https://gist.github.com/jhenstridge/a46236d699c1005cef5b829abfe069f6

Running this gave me the following output (with some paths elided):

```
Setting up signal watch
Sending signal
Removing signal watch
panic: send on closed channel

goroutine 35 [running]:
github.com/godbus/dbus.(*defaultSignalHandler).DeliverSignal.func1(0xc00011a000, 0xc000088050, 0xc0000ec000)
	src/github.com/godbus/dbus/default_handler.go:264 +0xbb
created by github.com/godbus/dbus.(*defaultSignalHandler).DeliverSignal
	src/github.com/godbus/dbus/default_handler.go:263 +0x1e3
panic: send on closed channel

goroutine 18 [running]:
github.com/godbus/dbus.(*defaultSignalHandler).DeliverSignal.func1(0xc0000fa000, 0xc000088050, 0xc0000ec000)
	src/github.com/godbus/dbus/default_handler.go:264 +0xbb
created by github.com/godbus/dbus.(*defaultSignalHandler).DeliverSignal
	src/github.com/godbus/dbus/default_handler.go:263 +0x1e3
```
