### ISSUE TITLE
Cannot get godbus to connect to private instance of system bus.

### ISSUE THREAD

**Issue by KBassford** [godbus/dbus#183]
Hi Folks,
I have created an instance of DBus messagebus configured like the system bus. and started it using:
"dbus-daemon --config-file=/etc/dbusalt/system.conf" with an open minimalist configuration.
```
<!DOCTYPE busconfig PUBLIC "-//freedesktop//DTD D-Bus Bus Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/dbus/1.0/busconfig.dtd">
<!-- Completely open test configuration!  Do not overwrite real DBus
 configuration. Copy to /etc/dbusalt -->

<busconfig>
  <!-- If we fork, keep the user's original umask to avoid affecting
       the behavior of child processes. -->
  <keep_umask/>

  <!-- <type>system</type> -->

  <!-- Run as special user -->
  <user>messagebus</user>

  <!-- Fork into daemon mode -->
  <fork/>

  <!-- <standard_session_servicedirs /> -->
  
  <!-- Write a pid file -->
  <pidfile>/var/run/dbusalt/pid</pidfile>

  <!-- Only listen on a local socket. (abstract=/path/to/socket 
       means use abstract namespace, don't really create filesystem 
       file; only Linux supports this. Use path=/whatever on other 
       systems.) -->
  <listen>unix:path=/var/run/dbusalt/system_bus_socket</listen>

  <auth>ANONYMOUS</auth>
  <allow_anonymous/>

  <policy context="default">
    <!-- Allow anyone to own anything -->
    <allow own="*"/>
    <!-- Allow anyone to connect -->
    <allow user="*"/>
    <!-- Allow everything to be sent -->
    <allow send_destination="*" eavesdrop="true"/>
    <!-- Allow everything to be received -->
    <allow eavesdrop="true"/>
  </policy>


  <!-- raise the service start timeout to 40 seconds as it can timeout
       on the live cd on slow machines -->
  <limit name="service_start_timeout">60000</limit>

  <!-- the memory limits are 1G instead of say 4G because they can't exceed 32-bit signed int max -->
  <limit name="max_incoming_bytes">1000000000</limit>
  <limit name="max_outgoing_bytes">1000000000</limit>
  <limit name="max_message_size">1000000000</limit>
  <limit name="service_start_timeout">120000</limit>  
  <limit name="auth_timeout">240000</limit>
  <limit name="max_completed_connections">100000</limit>  
  <limit name="max_incomplete_connections">10000</limit>
  <limit name="max_connections_per_user">100000</limit>
  <limit name="max_pending_service_starts">10000</limit>
  <limit name="max_names_per_connection">50000</limit>
  <limit name="max_match_rules_per_connection">50000</limit>
  <limit name="max_replies_per_connection">50000</limit>
  <limit name="reply_timeout">300000</limit>

</busconfig>
```
The problem is that connection object returned by either ...
```
			os.Setenv("DBUS_SYSTEM_BUS_ADDRESS", "unix:path/var/run/dbusalt/system_bus_socket")
			fmt.Println("address:", os.Getenv("DBUS_SYSTEM_BUS_ADDRESS"))
			conn, err = dbus.SystemBus()
```
or 
```
			newSocket := "unix:path=/var/run/dbusalt/system_bus_socket"
			conn, err = dbus.Dial(newSocket)
```
silently fails to connect to the messagebus I have created, usually fails to throw an error, instead hangs forever.
(Please Note that if I set "os.Setenv("DBUS_SYSTEM_BUS_ADDRESS", "unix:path/var/run/dbusalt/system_bus_socket")" I get "no such file or directory", but if I set "os.Setenv("DBUS_SYSTEM_BUS_ADDRESS", "/var/run/dbusalt/system_bus_socket")" it will hang forever when it gets to "conn.Hello()" or any other interactive call to the messagebus.  "dbus-monitor" pointed at my instance never detects any activity.

Is there something that I have misconfigured?  Or is it possible that godbus cannot handle private DBus instances (I find this hard to believe)?
Please note that I can connect to the private messagebus using d-feet and dbus-send.

**Comment by jsouthworth** [comment]
If you use dbus.Dial you'll need to call Auth and Hello to finish the connection to the bus. I've never tried faking the bus address from within the process but you are missing the '=' in the DBus address.

**Comment by KBassford** [comment]
Thanks, I will try that this morning and report back.

**Comment by KBassford** [comment]
Hi Mr. Southworth,
had to rewrite the connect portion to be more in line with the Server example ...
```
func privateSystemBus() (conn *dbus.Conn, err error) {
	os.Setenv("DBUS_SYSTEM_BUS_ADDRESS", "unix:path=/var/run/dbusalt/system_bus_socket")
	conn, err = dbus.SystemBusPrivate()
	if err != nil {
		return nil, err
	}
	if err = conn.Auth([]dbus.Auth{dbus.AuthAnonymous()}); err != nil {
		conn.Close()
		conn = nil
		return
	}
	if err = conn.Hello(); err != nil {
		conn.Close()
		conn = nil
	}
	return conn, nil // success
}
```
Still working on Exports and RequestName() ...
so there is progress.

**Comment by KBassford** [comment]
Unfortunately I get through th function above, but cannot do anything with connection.  The portion of the code failing is ...
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x5de120]

goroutine 1 [running]:
github.com/godbus/dbus.(*Conn).Names(...)
	/home/kbassford/go/src/github.com/godbus/dbus/conn.go:378
main.main()
	/home/kbassford/go/src/local-gitlab.com/gkbassf/go-ladar/cmd/wifidaemon/daemon.go:137 +0x50
```
Export() and RequestName() all suffer the same root cause.

**Comment by jsouthworth** [comment]
Which version of the library are you using?

**Comment by KBassford** [comment]
Hi Mr. Southworth,
I used go get to pull it in.  Looks like the last time I updated it was on Jul 8th of this year.

**Comment by KBassford** [comment]
Just updated, opulled in a lot!

**Comment by KBassford** [comment]
Crap!  it works now.

**Comment by KBassford** [comment]
Thank you for being so patient with me.  Closing issue.
