### ISSUE TITLE
goroutine leak

### ISSUE THREAD

**Issue by mrunalp** [godbus/dbus#90]
Hi,
We are seeing goroutines leaked when using StartTransientUnit. Here is the backtrace of the leaking goroutines:
```
goroutine 8 [IO wait]:
net.runtime_pollWait(0x7f80b98cfe40, 0x72, 0xc4200c1778)
	/usr/lib/golang/src/runtime/netpoll.go:164 +0x5b
net.(*pollDesc).wait(0xc42005f878, 0x72, 0x1000, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:75 +0x3a
net.(*pollDesc).waitRead(0xc42005f878, 0xc4202447f0, 0x10)
	/usr/lib/golang/src/net/fd_poll_runtime.go:80 +0x36
net.(*netFD).readMsg(0xc42005f810, 0xc4202447f0, 0x10, 0x10, 0xc42014f320, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
	/usr/lib/golang/src/net/fd_unix.go:304 +0x21c
net.(*UnixConn).readMsg(0xc42000e0b0, 0xc4202447f0, 0x10, 0x10, 0xc42014f320, 0x1000, 0x1000, 0xc4202445fc, 0xc4200c9620, 0xc4202445c3, ...)
	/usr/lib/golang/src/net/unixsock_posix.go:115 +0x93
net.(*UnixConn).ReadMsgUnix(0xc42000e0b0, 0xc4202447f0, 0x10, 0x10, 0xc42014f320, 0x1000, 0x1000, 0xfc14b357c4, 0x7f80b9911db8, 0x7f, ...)
	/usr/lib/golang/src/net/unixsock.go:131 +0xac
github.com/opencontainers/runc/vendor/github.com/godbus/dbus.(*oobReader).Read(0xc42014f300, 0xc4202447f0, 0x10, 0x10, 0x1020, 0xc42014f300, 0x0)
	/root/gosrc/src/github.com/opencontainers/runc/vendor/github.com/godbus/dbus/transport_unix.go:21 +0x91
io.ReadAtLeast(0xfc15522c80, 0xc42014f300, 0xc4202447f0, 0x10, 0x10, 0x10, 0xfc152cac60, 0xfc15260b01, 0xc42014f300)
	/usr/lib/golang/src/io/io.go:307 +0xab
io.ReadFull(0xfc15522c80, 0xc42014f300, 0xc4202447f0, 0x10, 0x10, 0x28, 0x0, 0x0)
	/usr/lib/golang/src/io/io.go:325 +0x5a
github.com/opencontainers/runc/vendor/github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc4201ae010, 0xc4201a49f0, 0xc4200c1e00, 0xc42005f8a8)
	/root/gosrc/src/github.com/opencontainers/runc/vendor/github.com/godbus/dbus/transport_unix.go:85 +0x13a
github.com/opencontainers/runc/vendor/github.com/godbus/dbus.(*Conn).inWorker(0xc420097680)
	/root/gosrc/src/github.com/opencontainers/runc/vendor/github.com/godbus/dbus/conn.go:248 +0x4d
created by github.com/opencontainers/runc/vendor/github.com/godbus/dbus.(*Conn).Auth
	/root/gosrc/src/github.com/opencontainers/runc/vendor/github.com/godbus/dbus/auth.go:118 +0x74b
```
```

goroutine 11 [chan receive, 7 minutes]:
github.com/opencontainers/runc/vendor/github.com/godbus/dbus.(*Conn).outWorker(0xc4201c6000)
	/root/gosrc/src/github.com/opencontainers/runc/vendor/github.com/godbus/dbus/conn.go:385 +0x5c
created by github.com/opencontainers/runc/vendor/github.com/godbus/dbus.(*Conn).Auth
	/root/gosrc/src/github.com/opencontainers/runc/vendor/github.com/godbus/dbus/auth.go:119 +0x770
```

**Comment by jsouthworth** [comment]
Can you provide a bit more context about this problem. What are you seeing that you don't expect? What is the sequence that is causing you to see what you don't expect to see?

Based on just the stack trace all I can provide is that each connection has a few goroutines that are spawned to handle that connection. If the connection is closed the goroutines should go away. If the connection is not closed they will not. It is possible that this mechanism isn't working in the circumstance you have but I need some additional information.

Thanks!

**Comment by mrunalp** [comment]
@jsouthworth Never mind. user error. We weren't closing the connection resulting in the leaks. Thanks!
